package com.georgiiHadzhiev.entity;

public enum EventType {
    ROOM_CREATED,
    ROOM_UPDATED,
    ROOM_DELETED,
    ROOM_VIEWED,

    FILE_UPLOADED,
    RELATED_OBJECT_CREATED,
    RELATED_OBJECT_SOFT_DELETED,
    FILE_SOFT_DELETED,
    FILEMETADATA_VIEWED,
    FILE_DOWNLOADED,
    FILE_DELETED,

}
