server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: room-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/rooms/**
        - id: file-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/file/**
  security:
    oauth2:
      client:
        registration:
          keycloak-client:
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: H9tzBbQzbO72AGAmOfBt4oltb9bNHln8
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8282/realms/rooms-realm

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
